### ISSUE TITLE
Add features to crate to make it configurable

### ISSUE THREAD

**Issue by heinzelotto** [eclipse-heimlig/heimlig#148]
Would it make sense to add a Cargo feature to this library, so users can disable what they don't use, e. g. ecc?

**Comment by inorick** [comment]
The [architecture](https://github.com/eclipse-heimlig/heimlig/blob/main/doc/Architecture.md) is settled now: Heimlig has a generic core that controls the communication between clients and workers. Those workers either implement the required crypto algorithms themselves or control the hardware that does. This means that disabling an algorithm simply means not instantiating a worker for it. So I think we can do without cargo features for now.
