### ISSUE TITLE
Make sure GH actions is run also for PR's from forked repos

### ISSUE THREAD

**Issue by Nicoretti** [eclipse-heimlig/heimlig#21]
https://github.community/t/github-workflow-not-running-from-pull-request-from-forked-repository/16379/40

https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request_target

**Comment by inorick** [comment]
After moving to Eclipse, I do not think we will be needing this anymore.

**Comment by encbladexp** [comment]
I decided to unassign me, as I am not going to work on this :upside_down_face:
